
name: Deployment
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Packages
      run: yarn

    - name: Build page
      env:
        PUBLIC_URL: "/${{ github.event.repository.name }}/"
      run: |
        yarn build

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4.3.3
      with:
        clean: true
        branch: gh-pages
        folder: packages/front-end/dist
